name: Advanced ETL Docker Pipeline

on:
  push:
    paths:
      - 'etl-advanced-project/**'
  pull_request:
    paths:
      - 'etl-advanced-project/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t etl-advanced-project ./etl-advanced-project
      - name: Run Docker Container
        run: docker run --rm etl-advanced-project
