name: Advanced ETL Python Tests

on:
  push:
    paths:
      - 'etl-advanced-project/**'
  pull_request:
    paths:
      - 'etl-advanced-project/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          cd etl-advanced-project
          pip install -r requirements.txt
          pytest
